# Generated by Django 4.2.7 on 2024-01-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('batting_average', models.FloatField()),
                ('home_runs', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
