# Generated by Django 4.2.7 on 2024-01-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_player_delete_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('選手名', models.TextField()),
                ('守備', models.TextField()),
                ('生年月日', models.TextField()),
                ('年齢', models.IntegerField()),
                ('年数', models.IntegerField()),
                ('身長', models.IntegerField()),
                ('体重', models.IntegerField()),
                ('血液型', models.TextField()),
                ('投打', models.TextField()),
                ('出身地', models.TextField()),
                ('年俸', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
