# Generated by Django 4.2.7 on 2024-01-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0003_baseballplayer_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiantsHitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('背番号', models.TextField()),
                ('選手名', models.TextField()),
                ('打率', models.TextField()),
                ('試合', models.TextField()),
                ('打席数', models.TextField()),
                ('打数', models.TextField()),
                ('安打', models.TextField()),
                ('本塁打', models.TextField()),
                ('打点', models.TextField()),
                ('盗塁', models.TextField()),
                ('四球', models.TextField()),
                ('死球', models.TextField()),
                ('三振', models.TextField()),
                ('犠打', models.TextField()),
                ('併殺打', models.TextField()),
                ('出塁率', models.TextField()),
                ('長打率', models.TextField()),
                ('OPS', models.TextField()),
                ('RC27', models.TextField()),
                ('XR27', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BaseballPlayer',
        ),
    ]
