# Generated by Django 4.2.7 on 2024-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0005_cleague'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleague',
            name='三塁打',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='三振',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='二塁打',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='併殺打',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='出塁率',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='四球',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='塁打',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='安打',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='得点',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='打席数',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='打数',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='打点',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='打率',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='敬遠',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='本塁打',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='死球',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='犠打',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='犠飛',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='盗塁',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='盗塁刺',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='試合',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='長打率',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cleague',
            name='順位',
            field=models.IntegerField(),
        ),
    ]
